Repository 2024HongikFestival/Festa-Client-Application, pull requests merged in 2024-09, with the labels that each got.

#46 [Feat] 편의시설 페이지 i18next 적용 / 토글 디자인 변경
  src/i18n/resource/en.json
  src/i18n/resource/ko.json
  src/pages/facilities/FacilitiesPage.jsx
  src/pages/facilities/LostAndFoundSection.jsx
  src/pages/facilities/MedicalSection.jsx
  src/pages/facilities/RestroomSection.jsx
  src/pages/facilities/ToiletSection.jsx
  src/pages/facilities/styles.js
Labels: 💄 Design, 🧑‍💻 수연, 대동제

#47 [Feat] 와디페 메인페이지 i18next 적용
  src/i18n/resource/en.json
  src/i18n/resource/ko.json
  src/pages/flame/FlameMainPage.Styled.js
  src/pages/flame/FlameMainPage.jsx
Labels: 💄 Design, ✨ Feature, 🧑‍💻 채영, 와디페

#33 [Feat] Header / Footer / MenuBar / 플로팅 버튼 구현 / 개화 수정사항 반영 / i18next 적용
  src/App.jsx
  src/assets/svgs/layouts/up.svg
  src/assets/svgs/layouts/xBtnBlack.svg
  src/assets/svgs/layouts/xBtnWhite.svg
  src/assets/svgs/makers/flame.svg
  src/assets/svgs/makers/gaehwaInsta.svg
  src/assets/svgs/makers/mangaeInsta.svg
  src/assets/svgs/makers/rightArrow.svg
  src/assets/svgs/makers/rightArrowGray.svg
  src/assets/svgs/makers/wdfInsta.svg
  src/assets/webps/layouts/backBtn.webp
  src/assets/webps/layouts/backBtnBlack.webp
  src/assets/webps/layouts/globe.webp
  src/assets/webps/layouts/globeGray.webp
  src/assets/webps/makers/be4.webp
  src/assets/webps/makers/fe5.webp
  src/components/common/ContentContainer.jsx
  src/components/layouts/AdminMenuBar.jsx
  src/components/layouts/CommonMenuBar.jsx
  src/components/layouts/Footer.jsx
  src/components/layouts/FooterStyles.js
  src/components/layouts/Header.jsx
  src/components/layouts/HeaderStyles.js
  src/components/layouts/Layout.jsx
  src/components/layouts/RenderMenuItem.jsx
  src/components/layouts/useUpdateBeforeHeight.js
  src/components/makers/GaehwaCard.jsx
  src/constants/layouts/menuItems.js
  src/constants/layouts/routeConfig.js
  src/constants/makers/GaehwaContributors.js
  src/constants/makers/GaehwaContributors.jsx
  src/constants/makers/LikelionContributors.js
  src/constants/makers/LikelionContributors.jsx
  src/i18n/resource/en.json
  src/i18n/resource/ko.json
  src/pages/flame/FlameMainPage.Styled.js
  src/pages/makers/GaehwaPage.jsx
  src/pages/makers/LikelionPage.jsx
  src/styles/GlobalStyle.js
Labels: 💄 Design, ✨ Feature, ♻️ Refactoring, 🧑‍💻 수연

#44 [Feat] 분실물 페이지 i18next 적용 + 아이폰 SE 버튼 위치 조정(미디어 쿼리)
  src/assets/svgs/lost/KakaoLogo.svg
  src/assets/webps/lost/kakaoBackGround.webp
  src/components/lost-and-found/AddLostItem/Camera/CameraPage.jsx
  src/components/lost-and-found/AddLostItem/Camera/CameraPage.styled.js
  src/components/lost-and-found/AddLostItem/Register/Register.jsx
  src/components/lost-and-found/LostAndFoundPage/DropDown/DropDown.jsx
  src/components/lost-and-found/LostAndFoundPage/LostBottomSheet/LostBottomSheet.jsx
  src/components/lost-and-found/LostAndFoundPage/LostBottomSheet/LostBottomSheet.styled.js
  src/components/lost-and-found/LostAndFoundPage/LostModal/LostModal.jsx
  src/components/lost-and-found/LostAndFoundPage/LostModal/LostModal.styled.js
  src/i18n/resource/en.json
  src/i18n/resource/ko.json
  src/pages/lost-and-found/pages/LostAndFoundPage/LostAndFoundPage.jsx
Labels: 💄 Design, ✨ Feature, 🧑‍💻 준혁, 대동제

#49 [Feat] 와디페 프로모션 퍼블리싱 & i18next 적용
  src/assets/webps/wdfPromotion/금군양조.webp
  src/assets/webps/wdfPromotion/예거마이스터.webp
  src/assets/webps/wdfPromotion/인테이크.webp
  src/assets/webps/wdfPromotion/프루팁스.webp
  src/constants/wdfPromotion/data.json
  src/i18n/resource/en.json
  src/i18n/resource/ko.json
  src/pages/flame/promotion/FlamePromotionPage.jsx
Labels: 💄 Design, ✨ Feature, 🧑‍💻 동욱, 와디페

#50 [Feat] 와디페 메인페이지 슬라이드 구성 수정 및 라인업 정보 추가
  src/assets/webps/wdfLineup/asterLogo.webp
  src/assets/webps/wdfLineup/aster_z.webp
  src/assets/webps/wdfLineup/chanxer.webp
  src/assets/webps/wdfLineup/chanxerLogo.webp
  src/assets/webps/wdfLineup/choiLogo.webp
  src/assets/webps/wdfLineup/choi_s.webp
  src/assets/webps/wdfLineup/fine.webp
  src/assets/webps/wdfLineup/fineLogo.webp
  src/assets/webps/wdfLineup/joody.webp
  src/assets/webps/wdfLineup/joodyLogo.webp
  src/assets/webps/wdfLineup/juncoco.webp
  src/assets/webps/wdfLineup/juncocoLogo.webp
  src/assets/webps/wdfLineup/lozic.webp
  src/assets/webps/wdfLineup/lozicLogo.webp
  src/assets/webps/wdfLineup/nap_on_cloud.webp
  src/assets/webps/wdfLineup/naponcloudLogo.webp
  src/assets/webps/wdfLineup/rightback.webp
  src/assets/webps/wdfLineup/rightbackLogo.webp
  src/assets/webps/wdfLineup/rui.webp
  src/assets/webps/wdfLineup/ruiLogo.webp
  src/assets/webps/wdfLineup/sigmaLogo.webp
  src/assets/webps/wdfLineup/sigma_z.webp
  src/assets/webps/wdfLineup/tezz.webp
  src/assets/webps/wdfLineup/tezzLogo.webp
  src/assets/webps/wdfLineup/vandal_rock.webp
  src/assets/webps/wdfLineup/vandalrockLogo.webp
  src/assets/webps/wdfLineup/wooxi.webp
  src/assets/webps/wdfLineup/wooxiLogo.webp
  src/assets/webps/wdfLineup/yongsul.webp
  src/assets/webps/wdfLineup/yongsulLogo.webp
  src/pages/flame/FlameMainPage.Styled.js
  src/pages/flame/FlameMainPage.jsx
Labels: 💄 Design, 🧑‍💻 채영, 와디페

#48 [Feat] 대동제 관람정보, 홍익존 i18next 적용 & 9/8 QA 반영
  src/components/stage/LocationInfo.jsx
  src/components/stage/StageSchedule.jsx
  src/constants/stage/stageSchedule.json
  src/i18n/resource/en.json
  src/i18n/resource/ko.json
  src/pages/stage/HongikZonePage.jsx
  src/pages/stage/StageInfoPage.jsx
  src/pages/stage/styles/HongikZonePage.js
  src/pages/stage/styles/LineupPage.js
  src/pages/stage/styles/StageInfoPage.js
Labels: 💄 Design, ✨ Feature, 🧑‍💻 동욱, 대동제

#52 [Feat] 어드민 페이지 헤더 조건 추가
  src/components/layouts/Header.jsx
  src/components/layouts/Layout.jsx
  src/constants/layouts/routeConfig.js
  src/pages/admin/AdminEvent.jsx
  src/pages/admin/AdminPage.jsx
Labels: 👽️ API, ✨ Feature, 🧑‍💻 채영, 어드민

#51 [Feat] 대동제MD & 와디페MD i18next 적용
  src/App.jsx
  src/components/booth/MD.jsx
  src/constants/booth/mdList.js
  src/constants/wdfMD/data.json
  src/i18n/resource/en.json
  src/i18n/resource/ko.json
  src/pages/booth/merchandiser/MdPage.jsx
  src/pages/booth/merchandiser/MdPage.styled.js
  src/pages/flame/merchandiser/FlameMdPage.jsx
Labels: 💄 Design, ✨ Feature, 🧑‍💻 동욱, 대동제, 와디페

#45 [Feat] 대동제 이벤트 구현
  index.html
  package.json
  src/App.jsx
  src/assets/svgs/event/check.svg
  src/assets/svgs/event/frame.svg
  src/assets/svgs/event/highlight_long.svg
  src/assets/svgs/event/highlight_short.svg
  src/assets/svgs/event/kakaoLogo.svg
  src/assets/svgs/event/tvingLogo.svg
  src/assets/webps/event/form.webp
  src/assets/webps/event/graphic.webp
  src/assets/webps/event/raffle.webp
  src/assets/webps/event/shareIcon.webp
  src/auth/RedirectEvents.jsx
  src/components/event/CheckBox.jsx
  src/components/event/ErrorContainer.jsx
  src/components/event/NoticeTimeBox.jsx
  src/components/event/PhoneNumBox.jsx
  src/components/layouts/Header.jsx
  src/components/layouts/Layout.jsx
  src/components/lost-and-found/AddLostItem/Camera/CameraPage.jsx
  src/components/lost-and-found/AddLostItem/context/AuthProvider.jsx
  src/components/lost-and-found/AddLostItem/outlet/ProtectedRoute.jsx
  src/constants/layouts/routeConfig.js
  src/context/AuthProvider.jsx
  src/outlet/ProtectedRoute.jsx
  src/pages/event/CompleteEvent.jsx
  src/pages/event/EnterEvent.jsx
  src/pages/event/EventPage.jsx
  src/pages/event/SubmitEvent.jsx
  src/pages/event/enter/EnterEvent.jsx
  src/pages/event/enter/styled.js
  src/pages/event/main/EventPage.jsx
  src/pages/event/main/styled.js
  src/styles/fonts/MPLUS1-Black.ttf
  src/styles/theme.js
  src/utils/event/handleShare.js
  yarn.lock
Labels: 💄 Design, 👽️ API, ✨ Feature, 🧑‍💻 가영, 대동제

#53 [Design] 티빙 로고 이미지 수정
  src/assets/svgs/admin/tvingImg.svg
  src/components/admin/Participants.jsx
Labels: 💄 Design, 🧑‍💻 채영, 어드민

#54 [Feat] 와디페 라인업 데이터 추가
  src/i18n/resource/en.json
  src/i18n/resource/ko.json
  src/pages/flame/lineup/FlameLineupPage.jsx
  src/pages/flame/lineup/styles.js
Labels: ✨ Feature, 🧑‍💻 동욱, 와디페

#56 [Fix] 이벤트 어드민 QA 수정사항 반영
  src/components/admin/EntryDetail.jsx
  src/components/layouts/AdminMenuBar.jsx
Labels: 🔧 Fix, 🧑‍💻 채영, 어드민

#55 [Feat] 대동제 라인업 데이터 추가 & i18n 적용
  src/assets/webps/stageLineup/0925_1.webp
  src/assets/webps/stageLineup/0925_2.webp
  src/assets/webps/stageLineup/0925_3.webp
  src/assets/webps/stageLineup/0926_1.webp
  src/assets/webps/stageLineup/0926_2.webp
  src/assets/webps/stageLineup/0926_3.webp
  src/assets/webps/stageLineup/0927_1.webp
  src/assets/webps/stageLineup/0927_2.webp
  src/assets/webps/stageLineup/0927_3.webp
  src/assets/webps/stageLineup/mc.webp
  src/components/stage/LocationInfo.jsx
  src/constants/stage/stageSchedule.json
  src/i18n/resource/en.json
  src/i18n/resource/ko.json
  src/pages/stage/LineupPage.jsx
  src/pages/stage/styles/LineupPage.js
Labels: ✨ Feature, 🧑‍💻 동욱, 대동제

#57 [ Fix] 헤더 변경사항 반영 / 배경 backgroundStyles로 분리 / 메뉴바에 대동제 메인, 와디페 메인 추가
  src/assets/webps/layouts/hambergerMenuWhite.webp
  src/components/layouts/Header.jsx
  src/components/layouts/Layout.jsx
  src/constants/layouts/menuItems.js
  src/constants/layouts/routeConfig.js
  src/i18n/resource/en.json
  src/i18n/resource/ko.json
  src/pages/stage/styles/HongikZonePage.js
  src/pages/stage/styles/LineupPage.js
  src/pages/stage/styles/StageInfoPage.js
  src/utils/layouts/backgroundStyles.js
Labels: 💄 Design, ♻️ Refactoring, 🧑‍💻 수연, 대동제

#61 [Fix] Footer 설정 변경 및 내용 추가
  src/auth/RedirectEvents.jsx
  src/components/layouts/Footer.jsx
  src/components/layouts/FooterStyles.js
  src/components/layouts/Layout.jsx
  src/i18n/resource/en.json
  src/i18n/resource/ko.json
  src/pages/event/SubmitEvent.jsx
  src/pages/event/enter/EnterEvent.jsx
  src/pages/event/main/EventPage.jsx
Labels: 💄 Design, ✨ Feature, 🔧 Fix, 🧑‍💻 가영, 대동제, 와디페

#60 [Feat] 이벤트 페이지 번역
  src/App.jsx
  src/assets/svgs/event/highlight_en.svg
  src/components/event/ErrorContainer.jsx
  src/components/event/NoticeTimeBox.jsx
  src/i18n/resource/en.json
  src/i18n/resource/ko.json
  src/pages/event/SubmitEvent.jsx
  src/pages/event/enter/EnterEvent.jsx
  src/pages/event/main/EventPage.jsx
  src/pages/event/main/styled.js
Labels: ✨ Feature, 🧑‍💻 가영, 대동제

#63 [Feat] 와디페 사이트맵 페이지
  package.json
  src/assets/lotties/siteMap.json
  src/assets/webps/map/gm.webp
  src/assets/webps/map/image02_1.webp
  src/assets/webps/map/image02_2.webp
  src/assets/webps/map/master.webp
  src/assets/webps/map/redBull.webp
  src/assets/webps/map/sitemap.webp
  src/assets/webps/map/sugarlolo-2.webp
  src/assets/webps/map/sugarlolo.svg
  src/assets/webps/map/sugarlolo.webp
  src/i18n/resource/en.json
  src/i18n/resource/ko.json
  src/pages/flame/map/FlameMapPage.jsx
  src/pages/flame/map/styles.js
  yarn.lock
Labels: 💄 Design, ✨ Feature, 🧑‍💻 정인, 와디페

#64 [Feat] 이벤트 소셜 공유 기능
  src/pages/event/SubmitEvent.jsx
  src/utils/event/handleShare.js
Labels: 👽️ API, ✨ Feature, 🧑‍💻 가영, 대동제

#69 [Feat] 대동제 관람정보, 홍익존 지도 구현
  package.json
  src/assets/lotties/stageInfo/arrowAnimation.json
  src/assets/webps/hongikZone/hongikZoneMap.webp
  src/assets/webps/stageInfo/button_scale.webp
  src/assets/webps/stageInfo/map.webp
  src/assets/webps/stageInfo/map_2.webp
  src/assets/webps/stageInfo/map_2_4x.webp
  src/assets/webps/stageInfo/stageInfoMap_2.webp
  src/components/stage/LocationInfo.jsx
  src/pages/stage/HongikZonePage.jsx
  src/pages/stage/styles/HongikZonePage.js
  yarn.lock
Labels: ✨ Feature, 🧑‍💻 동욱, 대동제

#66 [Feat] 스크롤 애니메이션 작업(대동제, 와디페) & 홍익존 번역 수정
  src/constants/wdfMD/data.js
  src/constants/wdfMD/data.json
  src/constants/wdfPromotion/data.js
  src/constants/wdfPromotion/data.json
  src/i18n/resource/en.json
  src/i18n/resource/ko.json
  src/pages/flame/lineup/FlameLineupPage.jsx
  src/pages/flame/merchandiser/FlameMdPage.jsx
  src/pages/flame/promotion/FlamePromotionPage.jsx
  src/pages/stage/HongikZonePage.jsx
  src/pages/stage/LineupPage.jsx
  src/pages/stage/styles/LineupPage.js
Labels: ✨ Feature, 🔧 Fix, 🧑‍💻 동욱, 대동제, 와디페

#67 [Feat] 편의시설 지도 드래그 구현 & 토글 애니메이션 적용
  src/assets/webps/facilities/lostAndFoundMap.webp
  src/assets/webps/facilities/medMap.webp
  src/assets/webps/facilities/restroomMap.webp
  src/components/facilities/DraggableMap.jsx
  src/pages/facilities/FacilitiesPage.jsx
  src/pages/facilities/LostAndFoundSection.jsx
  src/pages/facilities/MedicalSection.jsx
  src/pages/facilities/RestroomSection.jsx
  src/pages/facilities/styles.js
Labels: 💄 Design, ✨ Feature, ♻️ Refactoring, 🧑‍💻 수연, 대동제

#74 [Fix] 대동제 메인페이지 suspense 관련 오류 해결
  src/pages/main/MainPage.jsx
Labels: 🔧 Fix, 🧑‍💻 채영, 대동제

#76 [Feat] 와디페 예매 페이지 번역 & 사전예매 데이터 추가
  src/i18n/resource/en.json
  src/i18n/resource/ko.json
  src/pages/flame/reservation/FlameReservationPage.jsx
Labels: ✨ Feature, 🧑‍💻 정인, 와디페

#73 [Fix] mobile 환경에서 생기는 이슈 해결
  src/assets/svgs/layouts/flame.svg
  src/assets/svgs/layouts/gaehwaInsta.svg
  src/assets/svgs/layouts/mangaeInsta.svg
  src/assets/svgs/layouts/wdfInsta.svg
  src/assets/webps/layouts/backBtn.webp
  src/assets/webps/layouts/backBtnBlack.webp
  src/assets/webps/layouts/flameFooterBg.webp
  src/assets/webps/layouts/hambergerMenuWhite.webp
  src/components/layouts/Footer.jsx
  src/components/layouts/FooterStyles.js
  src/components/layouts/HeaderStyles.js
  src/pages/flame/FlameMainPage.jsx
  src/pages/flame/merchandiser/styles.js
  src/pages/flame/promotion/FlamePromotionPage.jsx
  src/pages/main/MainPage.jsx
  src/pages/main/MainPage.styled.js
  src/pages/stage/styles/LineupPage.js
Labels: 💄 Design, 🔧 Fix, 🧑‍💻 수연, 대동제, 어드민

#71 [Feat] 대동제 로드맵 페이지 지도 구현
  package.json
  src/assets/webps/map/2step.webp
  src/assets/webps/map/bigmap.webp
  src/assets/webps/map/buttonscale.webp
  src/assets/webps/map/completemap.webp
  src/assets/webps/map/detailMap2.webp
  src/assets/webps/map/mapmap.webp
  src/assets/webps/map/small.webp
  src/assets/webps/map/zoomMap2.webp
  src/i18n/resource/en.json
  src/i18n/resource/ko.json
  src/pages/map/MapPage.jsx
  src/pages/map/map.webp
  src/pages/map/styles.js
Labels: 💄 Design, ✨ Feature, 🧑‍💻 정인, 대동제

#78 [Fix] 대동제 관람정보 & 와디페MD, 프로모션 이슈 해결
  src/components/stage/LocationInfo.jsx
Labels: 🔧 Fix, 🧑‍💻 동욱, 대동제, 와디페

#77 [Fix] 와디페 사이트맵 페이지 번역 이름 수정
  src/i18n/resource/en.json
  src/i18n/resource/ko.json
  src/pages/flame/map/FlameMapPage.jsx
  src/pages/flame/map/styles.js
Labels: 🔧 Fix, 🧑‍💻 정인

#72 [Feat] 분실물 센터 지도 기능 완성 / 최적화
  package.json
  src/assets/webps/lost/LostAndFoundLocation.webp
  src/components/lost-and-found/LostAndFoundPage/LostModal/CutomMap.jsx
  src/components/lost-and-found/LostAndFoundPage/LostModal/LostModal.jsx
  src/components/lost-and-found/LostAndFoundPage/LostModal/LostModal.styled.js
  src/i18n/resource/en.json
  src/i18n/resource/ko.json
  src/pages/lost-and-found/pages/LostAndFoundPage/LostAndFoundPage.jsx
  src/pages/lost-and-found/pages/LostAndFoundPage/LostAndFoundPage.styled.js
  yarn.lock
Labels: 💄 Design, ✨ Feature, 🧑‍💻 준혁, 대동제

#79 [Fix] 대동제 로드맵 en 파일 수정
  src/i18n/resource/en.json
Labels: 🔧 Fix, 🧑‍💻 정인, 대동제

#80 [Chore] 배포용 redirect uri 적용
  src/auth/OAuth.js
Labels: 🚀 Deploy, 🧑‍💻 가영

#81 [Fix] 타임테이블 콘솔에러 해결
  src/pages/flame/timetable/styles.js
Labels: 🔧 Fix, 🧑‍💻 정인, 와디페

#82 [ Refactor] 편의시설 지도 moveBtn 추가 / 페이지 확대 방지 / import 순서 정렬 / 섹션 폴더링
  src/App.jsx
  src/assets/webps/facilities/moveBtn.webp
  src/components/facilities/DraggableMap.jsx
  src/components/facilities/LostAndFoundSection.jsx
  src/components/facilities/MedicalSection.jsx
  src/components/facilities/RestroomSection.jsx
  src/components/layouts/CommonMenuBar.jsx
  src/components/layouts/Layout.jsx
  src/pages/facilities/FacilitiesPage.jsx
  src/pages/facilities/styles.js
  src/pages/makers/GaehwaPage.jsx
  src/pages/makers/LikelionPage.jsx
Labels: 💄 Design, 🧑‍💻 수연, 대동제

#84 [Refactor] 배포 환경 최적화 및 오류 수정
  index.html
  public/favicon.svg
  public/vite.svg
  src/assets/static/FlameTimeTablePage.jsx
  src/components/booth/fleamarket/FleamarketBottom.jsx
  src/components/booth/fleamarket/FleamarketEvent.jsx
  src/components/booth/fleamarket/FleamarketMap.jsx
  src/components/booth/fleamarket/FleamarketTop.jsx
  src/components/booth/fleamarket/PriceTable.jsx
  src/components/booth/fleamarket/RecordList.jsx
  src/components/booth/md/MD.jsx
  src/components/booth/pub/PubCard.jsx
  src/components/booth/pub/PubMap.jsx
  src/components/booth/pub/PubOperatingHour.jsx
  src/components/booth/ranking/Ranking.jsx
  src/components/facilities/LostAndFoundSection.jsx
  src/components/facilities/MedicalSection.jsx
  src/components/facilities/RestroomSection.jsx
  src/components/lost-and-found/LostAndFoundPage/DropDown/DropDown.styled.js
  src/components/makers/LikelionCard.jsx
  src/i18n/resource/en.json
  src/i18n/resource/ko.json
  src/pages/booth/BoothPage.jsx
  src/pages/booth/fleamarket/Fleamarket.jsx
  src/pages/booth/fleamarket/FleamarketDetail.jsx
  src/pages/booth/merchandiser/MdPage.jsx
  src/pages/flame/FlameMainPage.jsx
  src/pages/flame/lineup/FlameLineupPage.jsx
  src/pages/flame/merchandiser/FlameMdPage.jsx
  src/pages/flame/reservation/FlameReservationPage.jsx
  src/pages/flame/timetable/FlameTimeTablePage.jsx
  src/pages/lost-and-found/pages/AddLostItem/AddLostItem.jsx
  src/pages/map/MapPage.jsx
  src/pages/stage/LineupPage.jsx
Labels: 🐛 BugFix, ♻️ Refactoring, 🧑‍💻 가영, 대동제, 와디페

#85 [Fix] fix loading type
  src/pages/main/MainPage.jsx
Labels: 🐛 BugFix, 🧑‍💻 가영, 대동제

#88 [Fix] 푸터 및 flame 메인 이미지 모바일에서 화질 저하 이슈 해결 / favicon 라이트&다크 모드
  index.html
  public/faviconBlack.svg
  public/faviconWhite.svg
  src/components/layouts/Footer.jsx
  src/components/layouts/FooterStyles.js
  src/pages/flame/FlameMainPage.Styled.js
  src/pages/flame/FlameMainPage.jsx
Labels: 💄 Design, 🔧 Fix, 🧑‍💻 수연, 대동제, 어드민

#90 [Fix] 번역 오류 수정 및 폰트 cdn 삭제
  index.html
  src/i18n/resource/en.json
Labels: 🔧 Fix, 🧑‍💻 가영, 대동제

#87 [Refactor] Add dynamic import in Booth page, Fleamarket page
  src/assets/lotties/booth/like.json
  src/assets/webps/booth/background/fleamarketMainBackground.webp
  src/components/booth/fleamarket/FleamarketBottom.jsx
  src/components/booth/fleamarket/FleamarketTop.jsx
  src/components/booth/fleamarket/PriceTable.jsx
  src/components/booth/md/MD.jsx
  src/components/booth/pub/CarouselItem.jsx
  src/components/booth/pub/PubCard.jsx
  src/components/booth/pub/PubMap.jsx
  src/components/booth/ranking/Kind111.jsx
  src/components/booth/ranking/Kind113.jsx
  src/components/booth/ranking/Kind122.jsx
  src/components/booth/ranking/Kind123.jsx
  src/components/booth/ranking/Ranking.jsx
  src/constants/booth/fleamarketDetailList.js
  src/constants/booth/mdList.js
  src/constants/booth/pubList.js
  src/constants/booth/wowList.js
  src/i18n/resource/en.json
  src/i18n/resource/ko.json
  src/pages/booth/BoothPage.jsx
  src/pages/booth/BoothPage.styled.js
  src/pages/booth/fleamarket/Fleamarket.jsx
  src/pages/booth/fleamarket/FleamarketDetail.jsx
  vite.config.js
Labels: ♻️ Refactoring, 🧑‍💻 윤서, 대동제

#83 [Fix] 기본페이지 확대 제한 & 확대 민감도 조정 / 불필요한 코드 삭제
  src/components/stage/LocationInfo.jsx
  src/pages/map/MapPage.jsx
  src/pages/map/styles.js
Labels: 💄 Design, 🔧 Fix, 🧑‍💻 정인, 대동제

#92 [Fix] 배포환경 이슈(카메라 버튼 나타나지 않음, 전면카메라 고정) 해결
  src/assets/webps/lost/CameraBtn.webp
  src/assets/webps/lost/kakaoAuth.webp
  src/components/lost-and-found/AddLostItem/Camera/CameraPage.jsx
  src/components/lost-and-found/AddLostItem/Camera/CameraPage.styled.js
  src/components/lost-and-found/LostAndFoundPage/LostModal/CutomMap.jsx
  src/components/lost-and-found/LostAndFoundPage/LostModal/LostModal.jsx
  src/components/lost-and-found/LostAndFoundPage/LostModal/LostModal.styled.js
Labels: 🐛 BugFix, 🧑‍💻 준혁

#93 [Feat] PubMap 민감도 설정 및 이미지 변경 keyframe 추가
  src/components/booth/pub/CarouselItem.jsx
  src/components/booth/pub/PubMap.jsx
  src/components/booth/pub/styles.js
  src/pages/flame/map/FlameMapPage.jsx
  vite.config.js
Labels: 💄 Design, ✨ Feature, 🧑‍💻 윤서, 대동제

#89 [Fix] 와디페 이미지 lazy 로딩 추가 및 오류 수정
  src/assets/webps/main/mainExample.webp
  src/constants/wdfMain/djData.js
  src/constants/wdfMain/djLogo.js
  src/constants/wdfTimeTable/wdfTT.js
  src/i18n/resource/en.json
  src/pages/flame/FlameMainPage.jsx
  src/pages/flame/lineup/FlameLineupPage.jsx
  src/pages/flame/timetable/FlameTimeTablePage.jsx
Labels: ♻️ Refactoring, 🧑‍💻 채영, 와디페

#95 [Fix] 오류 수정 및 코드 리팩터링
  src/api/axios.js
  src/assets/svgs/event/highlight_en.svg
  src/assets/svgs/layouts/hambergerMenuGray.svg
  src/assets/webps/layouts/instaLogo.webp
  src/assets/webps/map/gm.webp
  src/assets/webps/map/image02_1.webp
  src/assets/webps/map/image02_2.webp
  src/assets/webps/map/mapmap.webp
  src/assets/webps/map/master.webp
  src/assets/webps/map/redBull.webp
  src/assets/webps/map/sugarlolo-2.webp
  src/assets/webps/map/sugarlolo.svg
  src/assets/webps/map/sugarlolo.webp
  src/assets/webps/map/zoomMap2.webp
  src/assets/webps/wdTT/DjImg.webp
  src/assets/webps/wdTT/timtablefullButtton.webp
  src/auth/RedirectEvents.jsx
  src/auth/RedirectLosts.jsx
  src/components/admin/BlockList.jsx
  src/components/admin/EntryDetail.jsx
  src/components/admin/Post.jsx
  src/components/booth/fleamarket/FleamarketBottom.jsx
  src/components/booth/fleamarket/FleamarketTop.jsx
  src/components/booth/fleamarket/PriceTable.jsx
  src/components/booth/pub/CarouselItem.jsx
  src/components/booth/pub/PubCarousel.jsx
  src/components/booth/ranking/Kind111.jsx
  src/components/booth/ranking/Kind113.jsx
  src/components/booth/ranking/Kind122.jsx
  src/components/booth/ranking/Kind123.jsx
  src/components/booth/ranking/Ranking.jsx
  src/components/event/ErrorContainer.jsx
  src/components/facilities/DraggableMap.jsx
  src/components/layouts/Footer.jsx
  src/components/lost-and-found/AddLostItem/Camera/CameraPage.styled.js
  src/components/lost-and-found/AddLostItem/Register/Register.jsx
  src/components/lost-and-found/LostAndFoundPage/LostBottomSheet/LostBottomSheet.styled.js
  src/components/lost-and-found/LostAndFoundPage/LostModal/CutomMap.jsx
  src/pages/event/enter/EnterEvent.jsx
  src/pages/event/main/EventPage.jsx
  src/pages/flame/FlameMainPage.jsx
  src/pages/flame/lineup/FlameLineupPage.jsx
  src/pages/flame/promotion/FlamePromotionPage.jsx
  src/pages/flame/timetable/FlameTimeTablePage.jsx
  src/pages/flame/timetable/styles.js
  src/pages/lost-and-found/pages/LostAndFoundPage/LostAndFoundPage.jsx
  src/pages/main/MainPage.jsx
  src/pages/stage/LineupPage.jsx
  src/pages/stage/styles/LineupPage.js
  src/utils/event/handleShare.js
  src/utils/stage/getSelectedDayByDate.js
Labels: 🐛 BugFix, ♻️ Refactoring, 🧑‍💻 가영

#96 [Feat] Insert Meta data in index.html
  index.html
  package.json
  src/i18n/resource/ko.json
  src/pages/booth/BoothPage.jsx
  src/pages/event/main/EventPage.jsx
  src/pages/flame/FlameMainPage.jsx
  src/pages/flame/lineup/FlameLineupPage.jsx
  src/pages/flame/map/FlameMapPage.jsx
  src/pages/flame/timetable/FlameTimeTablePage.jsx
  src/pages/lost-and-found/pages/LostAndFoundPage/LostAndFoundPage.jsx
  src/pages/main/MainPage.jsx
  src/pages/makers/LikelionPage.jsx
  src/pages/map/MapPage.jsx
  src/pages/stage/LineupPage.jsx
  yarn.lock
Labels: 🚀 Deploy, ♻️ Refactoring, 🧑‍💻 윤서, 🧑‍💻 가영

#97 [Fix] 인스타 로고 화질 저하 이슈 & 클릭 링크 연결 이슈 해결
  src/assets/webps/hongikZone/hongikZoneMap.webp
  src/components/layouts/Footer.jsx
  src/components/layouts/FooterStyles.js
Labels: 🐛 BugFix, 💄 Design, 🧑‍💻 수연, 대동제, 어드민

#100 [Refactor] 주점 랭킹 useMemo 추가
  src/components/booth/ranking/Ranking.jsx
Labels: ♻️ Refactoring, 🧑‍💻 윤서

#98 [Fix] 게시글 없을 때 무한 alert + 카메라 기본 0.5배 줌 수정 + 게시글 없을 때 텍스트 추가
  src/components/lost-and-found/AddLostItem/Camera/CameraPage.jsx
  src/i18n/resource/en.json
  src/i18n/resource/ko.json
  src/pages/lost-and-found/pages/LostAndFoundPage/LostAndFoundPage.jsx
  src/pages/lost-and-found/pages/LostAndFoundPage/LostAndFoundPage.styled.js
Labels: 🐛 BugFix, 💄 Design, ✨ Feature, 🧑‍💻 준혁

#102 [Chore] Add og:img
  public/openGraphImg.webp
Labels: ✨ Feature, 🧑‍💻 윤서

#103 [Chore] Fix og:image content
  index.html
  public/openGraphImg.webp
Labels: ♻️ Refactoring, 🧑‍💻 윤서

#108 [Feat] 유지보수 변경 사항 적용 (좋아요 하트 애니메이션 개수 증가 및 투명도 조정 & 플리마켓 아이콘 추가 & 미사용 패키지 삭제 등)
  package.json
  src/assets/webps/booth/background/fleamarketMainBackground.webp
  src/assets/webps/booth/icon/arrow.webp
  src/assets/webps/booth/map/boothMapImg.webp
  src/assets/webps/booth/map/pubMapDefault.webp
  src/assets/webps/booth/map/pubMapZoom.webp
  src/assets/webps/booth/mapExample.webp
  src/components/booth/fleamarket/FleamarketInfo.jsx
  src/components/booth/pub/PubCard.jsx
  src/components/booth/pub/PubOperatingHour.jsx
  src/components/booth/ranking/Kind111.jsx
  src/components/booth/ranking/Kind113.jsx
  src/components/booth/ranking/Kind122.jsx
  src/components/booth/ranking/Kind123.jsx
  src/components/lost-and-found/LostAndFoundPage/LostModal/CutomMap.jsx
  src/i18n/resource/en.json
  src/i18n/resource/ko.json
  src/pages/main/MainPage.jsx
  src/pages/main/MainPage.styled.js
  yarn.lock
Labels: 🐛 BugFix, 💄 Design, 🧑‍💻 윤서

#107 [Chore] 관람정보 > 학생중앙무대 오타 수정
  src/i18n/resource/en.json
  src/i18n/resource/ko.json
Labels: 🔧 Fix, 🧑‍💻 동욱, 대동제

#106 [ Feat] 유지보수 변경 사항 적용 (어드민 분실물 페이지 min-height 추가 및 와디페 메인 스와이퍼 상하 스크롤 방지)
  src/components/admin/Post.jsx
  src/pages/flame/FlameMainPage.jsx
Labels: 💄 Design, 🧑‍💻 채영, 어드민

#109 [Design] main 애니메이션 로티 수정
  src/assets/lotties/main/mainStart.json
  src/pages/main/MainPage.styled.js
Labels: 💄 Design, 🔧 Fix, 🧑‍💻 수연, 대동제

#105 [Design] 푸터 모달 galaxy에도 꽉 차도록 변경
  src/components/lost-and-found/LostAndFoundPage/LostBottomSheet/LostBottomSheet.styled.js
Labels: 💄 Design, 🧑‍💻 준혁, 대동제

#112 [Feat] 와디페 푸터 스놀 인스타 추가
  src/assets/svgs/layouts/snolInsta.svg
  src/components/layouts/Footer.jsx
Labels: ✨ Feature, 🧑‍💻 가영, 와디페

#113 [Fix] 주점 지도 파일 수정
  src/assets/webps/booth/map/defaultPubMap.webp
  src/assets/webps/booth/map/pubMapDefault.webp
  src/assets/webps/booth/map/pubMapZoom.webp
  src/assets/webps/booth/map/zoomPubMap.webp
  src/components/booth/pub/PubMap.jsx
Labels: 🚨 !HOTFIX, 🧑‍💻 가영, 대동제

#114 [Feat] Limit click count in 1 min and check consistancy
  src/components/booth/pub/CarouselItem.jsx
Labels: 🐛 BugFix, 🔧 Fix, 🧑‍💻 윤서, 대동제
